gpslogger/src/main/java/com/mendhak/gpslogger/common/OpenGTSClient.java, gpslogger/src/main/java/com/mendhak/gpslogger/senders/gdocs/GDocsJob.java, gpslogger/src/main/java/com/mendhak/gpslogger/senders/osm/OSMJob.java
Hi,
The timeout of HttpURLConnection and Apache HttpClient is 0, which means the request would never return if either connection or read timeouts, and the code would never catch these exceptions. 
This patch set explicit timeout value (10s for connection timeout and 30s for read timeout), so the code would catch and handle timeout exceptions as you would expect.
Best,
=> Add timeout for http requests

gpslogger/src/main/java/com/mendhak/gpslogger/GpsMainActivity.java, gpslogger/src/main/res/values/strings.xml
Hi, 
This patch adds several error message boxes "Could not upload the file" when uploading logger file fails. It is always a good practice to keep users aware if their operations did not work as expected. 
Best regards,
=> Show error message when uploading file failed

gpslogger/src/main/java/com/mendhak/gpslogger/loggers/Gpx10FileLogger.java
The gpx 10 schema [http://www.topografix.com/GPX/1/0/gpx.xsd](url) requires a specific sequence for the elements contained in a trkpt:
<xsd:sequence>    
<xsd:element name="trkpt"   minOccurs="0" maxOccurs="unbounded">
<xsd:complexType>
<xsd:sequence>  
<xsd:element name="ele"           type="xsd:decimal"      minOccurs="0"/>
<xsd:element name="time"          type="xsd:dateTime"     minOccurs="0"/>
<xsd:element name="course"        type="gpx:degreesType"  minOccurs="0"/>
<xsd:element name="speed"         type="xsd:decimal"      minOccurs="0"/>
<xsd:element name="magvar"        type="gpx:degreesType"  minOccurs="0"/>
<xsd:element name="geoidheight"   type="xsd:decimal"      minOccurs="0"/>
<xsd:element name="name"          type="xsd:string"       minOccurs="0"/>
<xsd:element name="cmt" …
=> fix schema violation in gpx10 logger.

gpslogger/src/main/java/com/mendhak/gpslogger/loggers/nmea/NmeaSentence.java
when parsing nmea sentences for hdop the type of sentence may not be qualified.
It looks like a recent bug was introduced in https://github.com/mendhak/gpslogger/commit/0589180e77e4758bad578fd520c3a3f8e0c989a4
=> fix error in parsing nmea sentences to get hdop.

gpslogger/src/main/java/com/mendhak/gpslogger/common/Strings.java, gpslogger/src/main/res/values/strings.xml, gpslogger/src/test/java/com/mendhak/gpslogger/common/StringsTest.java
%SEC for seconds
%DAYNAME for the three letter month name (fixed to english language, lowercased)
%MONTHNAME for the three letter month name (fixed to english language, lowercased)
Filenames like "gps--2017-05-24--wed--20-32-07.csv" are easier to find in a file browser (where's the file from last monday afternoon?).
=> Added 3 more placeholders for the custom file name generator.

gpslogger/src/main/res/layout/fragment_detailed_view.xml
I've fixed the behaviour described in issue #544 by adding a matching property to the relevant part of the fragments manifest.
=>  Fix #544: undesired scrolling in detailed view

gpslogger/build.gradle, gpsloggerwear/build.gradle, gradle/wrapper/gradle-wrapper.properties
Gradle 4.0 has been released.
Also a few updates in the support libraries provided by Google have been released. 
This PR reflects that.
=> Update Gradle to 4.0 and Google Libs

gpslogger/src/main/java/com/mendhak/gpslogger/GeneralLocationListener.java, gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java, gpslogger/src/main/java/com/mendhak/gpslogger/GpsMainActivity.java, gpslogger/src/main/java/com/mendhak/gpslogger/common/BundleConstants.java, gpslogger/src/main/java/com/mendhak/gpslogger/common/Locations.java, gpslogger/src/main/java/com/mendhak/gpslogger/common/Maths.java, gpslogger/src/main/java/com/mendhak/gpslogger/common/SerializableLocation.java, gpslogger/src/main/java/com/mendhak/gpslogger/common/events/UploadEvents.java, gpslogger/src/main/java/com/mendhak/gpslogger/loggers/csv/CSVFileLogger.java, gpslogger/src/main/java/com/mendhak/gpslogger/loggers/gpx/Gpx10FileLogger.java, gpslogger/src/main/java/com/mendhak/gpslogger/senders/GpxReader.java, gpslogger/src/test/java/com/mendhak/gpslogger/common/LocationsTest.java, gpslogger/src/test/java/com/mendhak/gpslogger/common/StringsTest.java, gpslogger/src/test/java/com/mendhak/gpslogger/loggers/csv/CSVFileLoggerTest.java, gpslogger/src/test/java/com/mendhak/gpslogger/loggers/customurl/CustomUrlLoggerTest.java, gpslogger/src/test/java/com/mendhak/gpslogger/loggers/gpx/Gpx10WriteHandlerTest.java
Your code uses string constants such as "PASSIVE" or "HDOP" at quite some places to use them to identify keys in the extras bundle. 
I've extracted them to a class for them to be used as constants to prevent mistakes with mismatching keys.
This PR is extracted from my current code base.
Caveat: There is one weird test that I had to `@ignore` in `StringsTest.java`. I've tried to debug what runs wrong there, however have not been able to identify the issue. It's a one-off issue when it comes to dates. Maybe you have some advice there. Ideally the PR would go in without having to `@ignore` things.
Also `UploadEvents.java` had a type that I could not resist to fix.
=> Externalize BundleConstants to Object

gpslogger/src/main/java/com/mendhak/gpslogger/common/Strings.java, gpslogger/src/main/java/com/mendhak/gpslogger/ui/fragments/display/GpsDetailedViewFragment.java, gpslogger/src/main/java/com/mendhak/gpslogger/ui/fragments/display/GpsSimpleViewFragment.java
do not allow altitude to scale to kilometers or miles.
This is a potential resolution for issue #576 .
=> Always use meters or feet for altitude display, i.e.

.travis.yml, README.md, build.gradle, gpslogger/build.gradle, gpsloggerwear/build.gradle, gradle/wrapper/gradle-wrapper.properties
- Upgraded to Gradle plugin 3.0.1 and Gradle 4.1
- Upgraded com.github.dmytrodanylyk.android-process-button to 1.0.4 to work with new build tools
- Configured project to use default build tools version on Gradle plugin
- Included google repo
=> Upgrades to work with Android Studio 3.0.1 and Gradle plugin 3.0.1 and Gradle 4.1

gpslogger/src/main/java/com/mendhak/gpslogger/common/PreferenceHelper.java, gpslogger/src/main/java/com/mendhak/gpslogger/common/PreferenceNames.java, gpslogger/src/main/java/com/mendhak/gpslogger/loggers/FileLoggerFactory.java, gpslogger/src/main/java/com/mendhak/gpslogger/loggers/gpx/Gpx10FileLogger.java, gpslogger/src/main/java/com/mendhak/gpslogger/loggers/gpx/Gpx11FileLogger.java, gpslogger/src/main/java/com/mendhak/gpslogger/ui/fragments/settings/LoggingSettingsFragment.java, gpslogger/src/main/res/values/strings.xml, gpslogger/src/main/res/xml/pref_logging.xml, gpslogger/src/test/java/com/mendhak/gpslogger/loggers/gpx/Gpx10AnnotateHandlerTest.java, gpslogger/src/test/java/com/mendhak/gpslogger/loggers/gpx/Gpx10WriteHandlerTest.java, gpslogger/src/test/java/com/mendhak/gpslogger/loggers/gpx/Gpx11WriteHandlerTest.java
Some websites (in particular Garmin connect) don't accept GPX 1.0 files any more.
I've extended the logger infrastructure to have a GPX11 logger that produces a GPX 1.1 compliant log file.
I've introduced a matching Preference so that if you choose to have GPX recording, you can choose between 1.0 and 1.1 (1.0 contains speed and course information which was dropped from the 1.1 spec it seems).
I've done some testing by recording on a physical device and then validating the GPX file according to the specification - seems to be fine.
I've also uploaded a recorded file to garmin and it works correctly.
=> add gpx 1.1 file format support

gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java
This code (from #353) is essentially useless, as it just calls `ResetCurrentFileName()`.  For the code to do what the PR claims to do, it should do:
```
//check if we change of day and then write the last position of yesterday as the first position of today
if (preferenceHelper.shouldCreateNewFileOnceADay()) {
SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
String today = sdf.format(new Date());
Location location = session.getCurrentLocationInfo();
if (!today.equals(Strings.getFormattedFileName()) && location != null) {
writeToFile(location);
}
}
```
=> Remove useless reset of filename

gpslogger/src/main/res/values/strings.xml
Add warning about system config overriding logging interval.
A little extra text here would have helped me work out faster why GPS Logger didn't seem to be respecting the interval I set.
Thank you for creating a great app!
=> Add warning about system doze

gpslogger/build.gradle, gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java, gpslogger/src/main/java/com/mendhak/gpslogger/GpsMainActivity.java, gpslogger/src/main/java/com/mendhak/gpslogger/common/Strings.java, gpslogger/src/main/java/com/mendhak/gpslogger/senders/customurl/CustomUrlManager.java, gpslogger/src/main/java/com/mendhak/gpslogger/ui/fragments/settings/CustomUrlFragment.java, gpslogger/src/main/res/values/strings.xml, gpslogger/src/test/java/com/mendhak/gpslogger/common/StringsTest.java, gpslogger/src/test/java/com/mendhak/gpslogger/loggers/gpx/Gpx11WriteHandlerTest.java, gpslogger/src/test/java/com/mendhak/gpslogger/senders/customurl/CustomUrlManagerTest.java
Issue #930
When switching profiles via automation, try to start logging again instead of waiting for time_before_logging to have elapsed.
Issue #951 
When closing the drawer, close the profile list.  
When clicking an item in the profile list, close the profile list, but keep the drawer open.   
(Limitation of the library, there's no method to keep the profile list open).  
Issue #944 
Custom URL parameter `%ALL` which gets replaced by every custom URL parameter available.  
Example:
https://example.com/?%ALL
Results in
https://example.com/?lat=37.421998333333335&lon=-122.084&sat=0&desc=&alt=5.0&acc=5.0&dir=0.0&prov=gps&spd=0.0&timestamp=1650655193&timeoffset=2022-04-22T20:19:53.228%2B01:00&time=2022-04-22T19:19:53.228Z&starttimestamp=1650655188&date=2022-04-22&batt=100.0&ischarging=false& …
=> Milestone 121

fastlane/metadata/android/en-US/changelogs/123.txt, gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java, gpslogger/src/main/java/com/mendhak/gpslogger/common/PreferenceHelper.java, gpslogger/src/main/java/com/mendhak/gpslogger/common/PreferenceNames.java, gpslogger/src/main/java/com/mendhak/gpslogger/common/network/ConscryptProviderInstaller.java, gpslogger/src/main/java/com/mendhak/gpslogger/ui/fragments/settings/GeneralSettingsFragment.java, gpslogger/src/main/res/xml/pref_general.xml
Issue #990
Add option to show **notification on lock screen.** Default is to hide it though. 
Issue #971 #979 
Added ability to install a **Conscrypt Provider**, (a separate APK) which provides TLS 1.3 capabilities to the app when connecting to various services.
=> Milestone 123 - Conscrypt Provider, and notification on lock screen.

assets/text/faq/faq16-custom-url.md, fastlane/metadata/android/en-US/changelogs/124.txt, gpslogger/src/main/java/com/mendhak/gpslogger/GpsMainActivity.java, gpslogger/src/main/java/com/mendhak/gpslogger/common/network/ConscryptProviderInstaller.java, gpslogger/src/main/res/values/strings.xml, gpslogger/src/main/res/xml/customurlsettings.xml
Issue #1000 - make the permission dialog undismissable
Issue #986  - clarify the difference between the custom url logging and autosend
Issue #1017  - bugfix, correct the signature for Conscrypt Provider on F-Droid
=> Milestone v124

assets/text/faq/faq16-custom-url.md, fastlane/metadata/android/en-US/changelogs/125.txt, gpslogger/src/main/java/com/mendhak/gpslogger/common/PreferenceHelper.java, gpslogger/src/main/java/com/mendhak/gpslogger/common/PreferenceNames.java, gpslogger/src/main/java/com/mendhak/gpslogger/loggers/FileLoggerFactory.java, gpslogger/src/main/java/com/mendhak/gpslogger/loggers/customurl/CustomUrlJob.java, gpslogger/src/main/java/com/mendhak/gpslogger/loggers/customurl/CustomUrlLogger.java, gpslogger/src/main/java/com/mendhak/gpslogger/senders/customurl/CustomUrlManager.java, gpslogger/src/main/res/values-hu/strings.xml, gpslogger/src/main/res/values/strings.xml, gpslogger/src/main/res/xml/customurlsettings.xml
Issue #1025
This change is to solve the following use case:
* Logging interval is 15 seconds.
* Custom url logging is enabled.
* There is no network connection for 3 hours.
* A custom url call takes around 500 milliseconds.
* This means after the phone has network connection again, it will take 6 minutes to send the queued requests.
* If only the current location is relevant for the user, there is no need to send all the previous locations. This decreases the number of requests and the delay until the current location is sent to the server.
A new switch is added to the customurlsettings page. This is false by default. In this case everything works as before.
If the flag is set to true, old custom url log jobs tagged with 'Discardable' will be removed from the queue when a new job is …
=> Add flag to custom url logging which can disable queueing requests while being offline

gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java
Issue #999
The use case was that after an Android version update the auto send did not run every minute anymore as defined in settings, but ran only every 5 minutes when the phone was idle.
This is based on commits ee96c9bd and e9521818 where a similar change was made with the alarms used for the logging interval.
The related issue is #969.
With `setAndAllowWhileIdle` the alarm might be delayed after the specified time passed when the phone is idle, while with `setExactAndAllowWhileIdle` the system will try to trigger the alarm exactly at the defined time.
=> Use exact alarms for auto send timers

gpslogger/src/main/res/drawable/gpslogger_monochrome.xml
The inset in the monochrome icon seems to break the icon when using certain themes. (In my case using the default theme on Nothing OS 2.0). Removing the inset makes the icon display properly.
Current icon:
After removing the inset:
=> Fix monochrome icon

gpslogger/src/main/java/com/mendhak/gpslogger/senders/customurl/CustomUrlManager.java, gpslogger/src/main/java/com/mendhak/gpslogger/ui/fragments/settings/CustomUrlFragment.java, gpslogger/src/main/res/values/strings.xml, gpslogger/src/test/java/com/mendhak/gpslogger/senders/customurl/CustomUrlManagerTest.java
Fixes #1139 
Add "%SPD_KPH" to parameter description dialog, add unit tests and modify speed values so floating point precision does not produce weird looking strings (e.g. 9001.0 * 3.6 = "32403.60000000004")
=> Feature: flyingOwl/custom_url_speed_in_kph

gpslogger/src/main/AndroidManifest.xml
[Official documentation](https://developer.android.com/develop/background-work/services/fg-service-types) states:
> Beginning with Android 14 (API level 34), you must declare an appropriate service type for each foreground service. That means you must declare the service type in your app manifest, and also request the appropriate foreground service permission for that type (in addition to requesting the [FOREGROUND_SERVICE](https://developer.android.com/reference/android/Manifest.permission#FOREGROUND_SERVICE) permission).
Since the app is declaring a service with `android:foregroundServiceType="location"`, [location section](https://developer.android.com/develop/background-work/services/fg-service-types#location) of the documentation specifies that permission …
=> Added android.permission.FOREGROUND_SERVICE_LOCATION to manifest.

fastlane/metadata/android/en-US/changelogs/133.txt, gpslogger/build.gradle, gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java, gpslogger/src/main/java/com/mendhak/gpslogger/GpsMainActivity.java, gpslogger/src/main/java/com/mendhak/gpslogger/MainPreferenceActivity.java, gpslogger/src/main/res/layout/activity_preferences.xml
Issue #1110 - fix for the layouts on Android 15. What a nightmare this new feature is. So much pointless busywork. 
Issue #1187 - auto send timer was causing the app to crash if the background work permission had been optimized or denied. I've now made it use Alarm Manager Compat.
=> Milestone 133

gpslogger/src/main/java/com/mendhak/gpslogger/GeneralLocationListener.java, gpslogger/src/main/java/com/mendhak/gpslogger/GpsLoggingService.java, gpslogger/src/main/java/com/mendhak/gpslogger/common/IntentConstants.java, gpslogger/src/main/java/com/mendhak/gpslogger/common/PreferenceHelper.java, gpslogger/src/main/java/com/mendhak/gpslogger/common/PreferenceNames.java, gpslogger/src/main/java/com/mendhak/gpslogger/common/Session.java, gpslogger/src/main/java/com/mendhak/gpslogger/ui/fragments/settings/PerformanceSettingsFragment.java, gpslogger/src/main/res/values-zh-rCN/strings.xml, gpslogger/src/main/res/values/strings.xml, gpslogger/src/main/res/xml/pref_performance.xml
Add passive data collection interval setting to prevent excessive data generation.
[#1211 I've also noticed that passiveLocationManager.requestLocationUpdates allows configuration of the sampling interval. Would it be possible to expose this as an independent configuration parameter?](https://github.com/mendhak/gpslogger/issues/1211#issuecomment-2781602312) 
```
passiveLocationManager.requestLocationUpdates(LocationManager.PASSIVE_PROVIDER, 1000, 0, passiveLocationListener);
passiveLocationManager.requestLocationUpdates(LocationManager.PASSIVE_PROVIDER, interval_time, 0, passiveLocationListener);
```
Attempted to implement interval control via passiveLocationManager.requestLocationUpdates, but discovered passive location updates are system-controlled …
=> Add passive data collection interval setting to prevent excessive data generation.
